//
export const CREATE_SERIES = 'CREATE_SERIES';
export const DELETE_SERIES = 'DELETE_SERIES';

// GET Series
export const FETCH_SERIES_START = 'FETCH_SERIES_START';
export const FETCH_SERIES_SUCCESS = 'FETCH_SERIES_SUCCESS';
export const FETCH_SERIES_FAILED = 'FETCH_SERIES_FAILED';

// POST Series
export const POST_SERIES_START = 'POST_SERIES_START';
export const POST_SERIES_SUCCESS = 'POST_SERIES_SUCCESS';
export const POST_SERIES_FAILED = 'POST_SERIES_FAILED';

// DELETE Series
export const DELETE_SERIES_START = 'DELETE_SERIES_START';
export const DELETE_SERIES_SUCCESS = 'DELETE_SERIES_SUCCESS';
export const DELETE_SERIES_FAILED = 'DELETE_SERIES_FAILED';

// UPDATE Series
export const UPDATE_SERIES_START = 'UPDATE_SERIES_START';
export const UPDATE_SERIES_SUCCESS = 'UPDATE_SERIES_SUCCESS';
export const UPDATE_SERIES_FAILED = 'UPDATE_SERIES_FAILED';
