//
export const CREATE_SEASON = 'CREATE_SEASON';
export const DELETE_SEASON = 'DELETE_SEASON';
export const UPDATE_SEASON = 'UPDATE_SEASON';

// GET Seasons
export const FETCH_SEASON_START = 'FETCH_SEASON_START';
export const FETCH_SEASON_SUCCESS = 'FETCH_SEASON_SUCCESS';
export const FETCH_SEASON_FAILED = 'FETCH_SEASON_FAILED';

// POST Season
export const POST_SEASON_START = 'POST_SEASON_START';
export const POST_SEASON_SUCCESS = 'POST_SEASON_SUCCESS';
export const POST_SEASON_FAILED = 'POST_SEASON_FAILED';

// DELETE Season
export const DELETE_SEASON_START = 'DELETE_SEASON_START';
export const DELETE_SEASON_SUCCESS = 'DELETE_SEASON_SUCCESS';
export const DELETE_SEASON_FAILED = 'DELETE_SEASON_FAILED';

// UPDATE Season
export const UPDATE_SEASON_START = 'UPDATE_SEASON_START';
export const UPDATE_SEASON_SUCCESS = 'UPDATE_SEASON_SUCCESS';
export const UPDATE_SEASON_FAILED = 'UPDATE_SEASON_FAILED';
