//
export const CREATE_COLUMN = 'CREATE_COLUMN';
export const DELETE_COLUMN = 'DELETE_COLUMN';

// GET COLUMN
export const FETCH_COLUMNS_START = 'FETCH_COLUMN_START';
export const FETCH_COLUMNS_SUCCESS = 'FETCH_COLUMN_SUCCESS';
export const FETCH_COLUMNS_FAILED = 'FETCH_COLUMN_FAILED';

// POST COLUMN
export const POST_COLUMN_START = 'POST_COLUMN_START';
export const POST_COLUMN_SUCCESS = 'POST_COLUMN_SUCCESS';
export const POST_COLUMN_FAILED = 'POST_COLUMN_FAILED';

// DELETE COLUMN
export const DELETE_COLUMN_START = 'DELETE_COLUMN_START';
export const DELETE_COLUMN_SUCCESS = 'DELETE_COLUMN_SUCCESS';
export const DELETE_COLUMN_FAILED = 'DELETE_COLUMN_FAILED';

// UPDATE COLUMN
export const UPDATE_COLUMN_START = 'UPDATE_COLUMN_START';
export const UPDATE_COLUMN_SUCCESS = 'UPDATE_COLUMN_SUCCESS';
export const UPDATE_COLUMN_FAILED = 'UPDATE_COLUMN_FAILED';
