//
export const CREATE_EPISODES = 'CREATE_EPISODES';
export const DELETE_EPISODES = 'DELETE_EPISODES';

// GET EPISODES
export const FETCH_EPISODES_START = 'FETCH_EPISODES_START';
export const FETCH_EPISODES_SUCCESS = 'FETCH_EPISODES_SUCCESS';
export const FETCH_EPISODES_FAILED = 'FETCH_EPISODES_FAILED';

// POST EPISODES
export const POST_EPISODES_START = 'POST_EPISODES_START';
export const POST_EPISODES_SUCCESS = 'POST_EPISODES_SUCCESS';
export const POST_EPISODES_FAILED = 'POST_EPISODES_FAILED';

// DELETE EPISODES
export const DELETE_EPISODE_START = 'DELETE_EPISODES_START';
export const DELETE_EPISODE_SUCCESS = 'DELETE_EPISODES_SUCCESS';
export const DELETE_EPISODE_FAILED = 'DELETE_EPISODES_FAILED';

// UPDATE EPISODES
export const UPDATE_EPISODE_START = 'UPDATE_EPISODES_START';
export const UPDATE_EPISODE_SUCCESS = 'UPDATE_EPISODES_SUCCESS';
export const UPDATE_EPISODE_FAILED = 'UPDATE_EPISODES_FAILED';
